Hw02 express
AlenaKabushko/nodejs-homework-rest-api pull request #1
Opened 2023-01-02 18:55 UTC by AlenaKabushko

2023-01-02 19:34 UTC, KhYulian commented on models/contacts.js
> +        return contactFromId
Можна скоротити return contacts.find()

2023-01-02 19:34 UTC, KhYulian commented on models/contacts.js
> +        return contactFromId
замість obj краще contact

2023-01-02 19:36 UTC, KhYulian commented on models/contacts.js
> +        if (body.phone) { contactFromId.phone = body.phone }
Використовуйте логічні оператори 
contactFromId.email = body.email || contactFromId.email - це один з варіантів

2023-01-02 19:37 UTC, KhYulian commented on models/contacts.js
> +
Пустота? :)

2023-01-02 19:38 UTC, KhYulian commented on routes/api/contacts.js
> +  }
if(!contactById ) {
  return  res.status(404).json({
      message: `We didn't find anyone with ID ${contactId}. Please try again`
    })
}
res.status(200).json(contactById)

2023-01-02 19:38 UTC, KhYulian commented on routes/api/contacts.js
> +  }
Валідацію винесіть в окрему middleware яка спрацьовуватиме перед контроллером

2023-01-02 19:39 UTC, KhYulian commented on routes/api/contacts.js
> +  } else {
Для цього у вас має бути схема правильно налаштована Joi

2023-01-02 19:39 UTC, KhYulian commented on routes/api/contacts.js
> +    // eslint-disable-next-line no-unused-vars
eslint-disable не використовуйте - виправте помилку

2023-01-02 19:40 UTC, KhYulian commented on utils/validSchema.js
> +});
const validSchemaPut = Joi.object({
  name: Joi.string().min(1).max(40),
  email: Joi.string().email(),
  phone: Joi.number().integer(),
}).min(1); - хоча б одне поле

2023-01-02 19:41 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-02 19:41 UTC, KhYulian commented
Також відписуйте на коменти по мірі виправлення)

2023-01-04 10:55 UTC, AlenaKabushko commented on models/contacts.js
> +        return contactFromId
скоротила, виправила)
просто більш подобається вертати змінну, ніж вираз)

2023-01-04 11:06 UTC, AlenaKabushko commented on models/contacts.js
> +
null?) якщо я вірно зрозуміла, то для того, щоб спрацювали таби, для гарного запису в JSON, null пропускає replacer.

2023-01-04 11:07 UTC, KhYulian commented on models/contacts.js
> +
я не про null в catch нічого немає просто пуста строка

2023-01-04 11:07 UTC, KhYulian commented on models/contacts.js
> +        return contactFromId
Можна і змінну, але зазвичай скорочують :)

2023-01-04 11:08 UTC, AlenaKabushko commented on models/contacts.js
> +
ой, точно ) дякую)

2023-01-04 17:15 UTC, AlenaKabushko commented on models/contacts.js
> +        if (body.phone) { contactFromId.phone = body.phone }
точно, но то ж не велика помилка?) чи це все з досвідом приходить?)

2023-01-04 17:15 UTC, AlenaKabushko commented on models/contacts.js
> +
є)

2023-01-04 17:16 UTC, AlenaKabushko commented on routes/api/contacts.js
> +  }
є) тут теж не прямо помилка, як помилка? просто не дуже логічний запис?)

2023-01-04 17:16 UTC, AlenaKabushko commented on routes/api/contacts.js
> +    // eslint-disable-next-line no-unused-vars
є) то все моя любов до змінних)

2023-01-04 17:26 UTC, KhYulian commented on models/contacts.js
> +        if (body.phone) { contactFromId.phone = body.phone }
Це не помилка, просто не найоптимальнійший варіант :)

2023-01-04 17:29 UTC, AlenaKabushko commented on routes/api/contacts.js
> +  } else {
зробила, мабуть так, але то  ж тоді загальна валідація на все? не будє окремого повідомлення, що нема поля?

2023-01-04 17:30 UTC, AlenaKabushko commented on utils/validSchema.js
> +});
+

2023-01-04 19:39 UTC, AlenaKabushko commented on routes/api/contacts.js
> +  }
зробила, тепер прямо так гарно виглядає)

2023-01-04 20:08 UTC, KhYulian approved these changes
Чудова робота ❤️❤️❤️

2023-01-04 20:08 UTC, merged