Hw03 mongodb
AlenaKabushko/nodejs-homework-rest-api pull request #2
Opened 2023-01-14 20:06 UTC by AlenaKabushko

2023-01-15 07:12 UTC, KhYulian commented on app.js
> +    });
Можна скоротити використайте ||

2023-01-15 07:14 UTC, KhYulian commented on controller/controller.js
> +  }
Використайте схему Joi, та middleware для валідації

2023-01-15 07:14 UTC, KhYulian commented on server.js
> +main();
Можна використати IIFE

2023-01-15 07:14 UTC, KhYulian commented on utils/tryCatch.js
> +
Використовуйте класи https://javascript.info/custom-errors

2023-01-15 07:15 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-15 13:41 UTC, AlenaKabushko commented on app.js
> +    });
трошки не зрозуміла, саме цей запис або с наступним if-ом?

2023-01-15 13:55 UTC, AlenaKabushko commented on controller/controller.js
> +  }
є)

2023-01-15 14:05 UTC, AlenaKabushko commented on server.js
> +main();
є)

2023-01-15 16:39 UTC, AlenaKabushko commented on utils/tryCatch.js
> +
додала класс валідації

2023-01-15 17:21 UTC, AlenaKabushko commented on utils/tryCatch.js
> +
трохи переробила помилки

2023-01-17 07:57 UTC, KhYulian commented on app.js
> +    });
return res.status(error.status || 500).json(...

2023-01-17 07:58 UTC, KhYulian approved these changes
Чудова робота :) Коменти візьміть до уваги при роботі над наступною

2023-01-17 07:58 UTC, merged